# Generated by Django 5.0.3 on 2024-03-21 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(max_length=200)),
                ('endpoint', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Running'), ('C', 'Completed'), ('F', 'Failed')], max_length=10)),
                ('meta', models.CharField(max_length=1024)),
                ('s3_bucket', models.CharField(max_length=254)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.environment')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1024)),
                ('uuid', models.UUIDField()),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('shasum', models.CharField(max_length=200)),
                ('s3_key', models.CharField(max_length=1024)),
                ('s3_version', models.CharField(max_length=254)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.deployment')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('job', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=1024)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.deployment')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.environment')),
            ],
        ),
    ]
